---
title: "Untitled"
author: "Guilherme Fernandes"
date: "13/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 0,echo=FALSE}
library(dplyr)
library(tibble)
library(ggplot2)
library(apsrtable)
library(stargazer)
library(pastecs)
library(readxl)
library(GoodmanKruskal)
library(gridExtra)
library(sjPlot)
library(pROC)
load("C:/Users/guife/Downloads/MIF.RData")
MIF$racacor=as.factor(MIF$racacor)
MIF$esc=as.factor(MIF$esc)
MIF$idade=(as.numeric(MIF$idade)-400)
MIF$lococor=as.factor(MIF$lococor)
MIF<- MIF %>%
  add_column(year = as.numeric(substr(MIF$dtobito,nchar(MIF$dtobito)-3,nchar(MIF$dtobito))))
MIF$ufinform=as.factor(MIF$ufinform)
MIF$obitopuerp=as.numeric(MIF$obitopuerp)
MIF$obitograv=as.numeric(MIF$obitograv)
MIF$tppos=as.factor(MIF$tppos)
MIF$estciv=as.factor(MIF$estciv)
MIF<- MIF %>%
  add_column(investigacao = if_else(MIF$tppos=="S","Investigado","Nao investigado"))
MIF<- MIF %>%
  add_column(maternoounao = if_else(MIF$obitograv==1,"materno",if_else(MIF$obitopuerp==1,"materno",if_else(MIF$obitopuerp%in%c(2,3),"nao materno",NULL))))
MIF<- MIF %>%
  add_column(maternalornot = if_else(MIF$tpobitocor%in%c(1,2,3,4),"materno",if_else(MIF$tpobitocor%in%c(5,6,7,8),"nao materno",NULL)))
MIF<- MIF %>%
  add_column(altcausa = if_else(MIF$tppos=="S",if_else(MIF$causabas==MIF$causabas_o,"nao alterado","alterado"),NULL))
levels(MIF$esc)=c("nenhuma","fundamental I","fundamental II","ensino medio","superior incompleto","superior completo","ignorado")
levels(MIF$racacor)=c("branca","preta","amarela","parda","ignorado")
levels(MIF$lococor)=c("hospital","outro estab saude","domicilio","via publica","outros","aldeia","ignorado")
levels(MIF$estciv)=c("solteira","casada","viuva","separada","uniao estavel","ignorado")
levels(MIF$ufinform)=c("Rondônia","Acre","Amazonas","Roraima","Pará","Amapá","Tocantins","Maranhão","Piauí","Ceará","Rio Grande do Norte","Paraíba","Pernambuco","Alagoas","Sergipe","Bahia","Minas Gerais","Espírito Santo","Rio de Janeiro","São Paulo","Paraná","Santa Catarina","Rio Grande do Sul","Mato Grosso do Sul","Mato Grosso","Goiás","Distrito Federal	")
MIF$estciv=droplevels(MIF$estciv)
MIF$maternoounao=as.factor(MIF$maternoounao)
MIFF=subset(MIF,tppos=="S")
MIFF<- MIFF %>%
  add_column(altcausamat = if_else(MIFF$maternoounao==MIFF$maternalornot,"nao alterado","alterado"))
mif10=subset(MIF,year=="2010")
miff10=subset(mif10,tppos=="S")
mifff10=subset(mif10,maternoounao=="materno")
MIFF10=subset(MIFF,year=="2010"&altcausamat=="alterado")
w10=summary(MIFF10$ufinform)
z10=summary(mifff10$ufinform)
x10=summary(mif10$ufinform)
y10=summary(miff10$ufinform)
mif11=subset(MIF,year=="2011")
miff11=subset(mif11,tppos=="S")
mifff11=subset(mif11,maternoounao=="materno")
MIFF11=subset(MIFF,year=="2011"& altcausamat=="alterado")
w11=summary(MIFF11$ufinform)
z11=summary(mifff11$ufinform)
x11=summary(mif11$ufinform)
y11=summary(miff11$ufinform)
mif12=subset(MIF,year=="2012")
miff12=subset(mif12,tppos=="S")
mifff12=subset(mif12,maternoounao=="materno")
MIFF12=subset(MIFF,year=="2012"& altcausamat=="alterado")
w12=summary(MIFF12$ufinform)
z12=summary(mifff12$ufinform)
x12=summary(mif12$ufinform)
y12=summary(miff12$ufinform)
mif13=subset(MIF,year=="2013")
miff13=subset(mif13,tppos=="S")
mifff13=subset(mif13,maternoounao=="materno")
MIFF13=subset(MIFF,year=="2013"& altcausamat=="alterado")
w13=summary(MIFF13$ufinform)
z13=summary(mifff13$ufinform)
x13=summary(mif13$ufinform)
y13=summary(miff13$ufinform)
mif14=subset(MIF,year=="2014")
miff14=subset(mif14,tppos=="S")
mifff14=subset(mif14,maternoounao=="materno")
MIFF14=subset(MIFF,year=="2014"& altcausamat=="alterado")
w14=summary(MIFF14$ufinform)
z14=summary(mifff14$ufinform)
x14=summary(mif14$ufinform)
y14=summary(miff14$ufinform)
mif15=subset(MIF,year=="2015")
miff15=subset(mif15,tppos=="S")
mifff15=subset(mif15,maternoounao=="materno")
MIFF15=subset(MIFF,year=="2015"& altcausamat=="alterado")
w15=summary(MIFF15$ufinform)
z15=summary(mifff15$ufinform)
x15=summary(mif15$ufinform)
y15=summary(miff15$ufinform)
mif16=subset(MIF,year=="2016")
miff16=subset(mif16,tppos=="S")
mifff16=subset(mif16,maternoounao=="materno")
MIFF16=subset(MIFF,year=="2016"& altcausamat=="alterado")
w16=summary(MIFF16$ufinform)
z16=summary(mifff16$ufinform)
x16=summary(mif16$ufinform)
y16=summary(miff16$ufinform)
mif17=subset(MIF,year=="2017")
miff17=subset(mif17,tppos=="S")
mifff17=subset(mif17,maternoounao=="materno")
MIFF17=subset(MIFF,year=="2017"& altcausamat=="alterado")
w17=summary(MIFF17$ufinform)
z17=summary(mifff17$ufinform)
x17=summary(mif17$ufinform)
y17=summary(miff17$ufinform)
mif18=subset(MIF,year=="2018")
miff18=subset(mif18,tppos=="S")
mifff18=subset(mif18,maternoounao=="materno")
MIFF18=subset(MIFF,year=="2018"& altcausamat=="alterado")
w18=summary(MIFF18$ufinform)
z18=summary(mifff18$ufinform)
x18=summary(mif18$ufinform)
y18=summary(miff18$ufinform)
mif19=subset(MIF,year=="2019")
miff19=subset(mif19,tppos=="S")
mifff19=subset(mif19,maternoounao=="materno")
MIFF19=subset(MIFF,year=="2019"& altcausamat=="alterado")
w19=summary(MIFF19$ufinform)
z19=summary(mifff19$ufinform)
x19=summary(mif19$ufinform)
y19=summary(miff19$ufinform)
tab=matrix(c(rep(c(2010),28),rep(c(2011),28),rep(c(2012),28),rep(c(2013),28),rep(c(2014),28),rep(c(2015),28),rep(c(2016),28),rep(c(2017),28),rep(c(2018),28),rep(c(2019),28),rep(c("RO","AC","AM","RR","PA","AP","TO","MA","PI","CE","RN","PB","PE","AL","SE","BA","MG","ES","RJ","SP","PR","SC","RS","MS","MT","GO","DF","NA"),10),y10/x10,y11/x11,y12/x12,y13/x13,y14/x14,y15/x15,y16/x16,y17/x17,y18/x18,y19/x19,z10/x10,z11/x11,z12/x12,z13/x13,z14/x14,z15/x15,z16/x16,z17/x17,z18/x18,z19/x19,w10/y10,w11/y11,w12/y12,w13/y13,w14/y14,w15/y15,w16/y16,w17/y17,w18/y18,w19/y19),nrow=280,ncol=5)
colnames(tab) <- c("Ano","Estado","% de invest","% de mater","% de reclass")
tabela=as.table(tab)
write.table(tabela,file="tabela.txt",sep = "\t",col.names = TRUE)
```
